# Generated by Django 5.2.7 on 2025-10-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('hash_value', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='part',
        ),
        migrations.DeleteModel(
            name='BOM',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
