# Generated by Django 5.2.7 on 2025-10-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_herramienta_remove_inventory_part_delete_bom_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Herramienta',
            new_name='InventoryItem',
        ),
    ]
