# Generated by Django 5.2.7 on 2025-10-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('repairs', '0002_reportearreglo_delete_repairrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('arreglo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repairs.reportearreglo')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
