# Generated by Django 5.2.7 on 2025-10-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Letal', 'Letal'), ('Grave', 'Grave'), ('Moderado', 'Moderado'), ('Minimo', 'Mínimo')], max_length=50)),
                ('gravedad', models.CharField(choices=[('Letal', 'Letal'), ('Grave', 'Grave'), ('Moderado', 'Moderado'), ('Minimo', 'Mínimo')], max_length=10)),
                ('condicion', models.CharField(choices=[('Dañado', 'Dañado'), ('Reparado', 'Reparado')], max_length=10)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('id_unico', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('dias_espacio', models.IntegerField()),
                ('carga', models.CharField(max_length=50)),
                ('estado_comunicacion', models.CharField(max_length=50)),
                ('version_software', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DroneEvent',
        ),
        migrations.RemoveField(
            model_name='telemetrydata',
            name='sensor',
        ),
        migrations.AddField(
            model_name='reportedano',
            name='telemetria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='drones.telemetria'),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='TelemetryData',
        ),
    ]
